version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-10.13
    steps:
      - checkout
      - run: npm build

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
