version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: npm build

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build